ALTER TABLE student
    age TEXT DEFAULT 20
    ADD CONSTRAINT age_constraint CHECK (age > 16);
ALTER COLUMN name SET NOT NULL;
    ALTER COLUMN name TEXT UNIQUE

ALTER TABLE faculty
ALTER COLUMN name TEXT UNIQUE
    ALTER COLUMN color TEXT UNIQUE